name: mlops-project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - imbalanced-learn>=0.11.0
  - mlflow
  - dvc
  - prefect
  - seaborn
  - notebook
  - plotly
  - pydotplus
  - xgboost
  - pip
  - flask
  - flask-cors
  - pytest
  - lightgbm
  - category_encoders
  - gunicorn
  - pip:
      - keras
      - tensorflow
      - brotli
      - aiodns>=1.1.1
      - msgpack>=0.6.2
